name: Sync Post

# Controls when the workflow will run
on:
  # schedule:
  #   - cron: "30 1 * * *"
  # https://docs.github.com/cn/developers/webhooks-and-events/events/issue-event-types
  issues:
    types:
      - opened
      - closed
      - edited
      - renamed
      - labeled
      - unlabeled
      - reopened
      - committed # ä¿®æ”¹ï¼Ÿ
  workflow_dispatch:

permissions:
  contents: write
  
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_USER: ${{ secrets.GH_USER }}
  GH_PROJECT_NAME: ${{ secrets.GH_PROJECT_NAME }}
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup Node.js ğŸš€
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0' # æŒ‡å®šå…·ä½“çš„ç‰ˆæœ¬å·

      - name: Git config ğŸ”§
        run: |
          git config --global user.name "zhaozhongming"
          git config --global user.email "coderzzm@foxmail.com"

      - name: Display runtime info âœ¨
        run: |
          echo 'å½“å‰ç›®å½•ï¼š'
          pwd
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.6.0 # æˆ–è€…æ‚¨æƒ³è¦ä½¿ç”¨çš„ pnpm ç‰ˆæœ¬

      - name: Install ğŸ”§
        run: pnpm install

      # - name: Build â›ï¸
      #   run: pnpm run build

      - name: Update blog files â›ï¸
        run: |
          echo "ğŸš€ å¼€å§‹åŒæ­¥æ–‡ç« ..."
          pnpm run sync-post && \
          echo "âœ… æ–‡ç« åŒæ­¥å®Œæˆï¼Œå¼€å§‹ç”Ÿæˆ RSS..."
          pnpm run generate-rss && \
          echo "âœ… RSS ç”Ÿæˆå®Œæˆ"
          git add . && \
          git commit -m 'chore(ci): blog sync'

      - name: Pull latest changes from remote
        run: git pull --rebase origin main

      - name: Push changes to remote
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ secrets.GH_USER }}/${{ secrets.GH_PROJECT_NAME }}.git"
          git push
